# Generated by Django 4.2.1 on 2023-06-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CART', '0002_account_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Totalprice',
        ),
    ]
