# Generated by Django 4.2.1 on 2023-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CART', '0003_remove_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Totalprice',
            field=models.IntegerField(default=1),
        ),
    ]
